title: Michael T. Siever # your name (or website title) here
logo: "/images/MichaelSieverHeadshotCrop.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Web/Software Developer. Programmer for 2+ years. Recent Austin Community College Graduate. Associate's Degree in Computer Information Technology - Computer Programming.
  <br><br>
  <a href="https://www.linkedin.com/in/michael-siever-b4656a41/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
